/*
 * REST API For Access To TURN Services
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/l7mp/stunner-auth-service/internal/auth"
	swagger "github.com/l7mp/stunner-auth-service/internal/handler"
)

func main() {
	log.Printf("Server started")
	auth.ReadConfigFromFile()
	router := swagger.NewRouter()

	log.Fatal(http.ListenAndServe("0.0.0.0:8080", router))
}
