/*
 * REST API For Access To TURN Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_api_models

// asdasdasd
type TurnAuthenticationToken struct {
	Username string `json:"username"`

	Password string `json:"password"`

	Ttl int64 `json:"ttl"`

	Uris []string `json:"uris"`
}
