/*
 * REST API For Access To TURN Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_api_models

// asdasdasd
type IceAuthenticationToken struct {
	Url []string `json:"url"`

	Username string `json:"username"`

	Credential string `json:"credential"`
}

type IceConfig struct {
	IceServers         []IceAuthenticationToken `json:"iceServers"`
	IceTransportPolicy string                   `json:"iceTransportPolicy,omitempty"`
}
