/*
 * REST API For Access To TURN Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"authhandler/auth_generation"
	swagger "authhandler/swagger_api_impl"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")
	auth_generation.ReadConfigFromFile()
	router := swagger.NewRouter()

	log.Fatal(http.ListenAndServe("0.0.0.0:8080", router))
}
