/*
 * REST API For Access To TURN Services
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// IceAuthenticationToken represents a TURN authentication token.
type IceAuthenticationToken struct {
	Url []string `json:"url"`

	Username string `json:"username"`

	Credential string `json:"credential"`
}

// IceConfig is an ICE server config stanza.
type IceConfig struct {
	IceServers         []IceAuthenticationToken `json:"iceServers"`
	IceTransportPolicy string                   `json:"iceTransportPolicy,omitempty"`
}
