/*
 * REST API For Access To TURN Services
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// TurnAuthenticationToken is an authentication token as of draft-uberti-behave-turn-rest-00 (https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00).
type TurnAuthenticationToken struct {
	Username string `json:"username"`

	Password string `json:"password"`

	Ttl int64 `json:"ttl"`

	Uris []string `json:"uris"`
}
