/*
 * REST API For Access To TURN Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_api_impl

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{

	Route{
		"GetIceAuth",
		strings.ToUpper("Get"),
		"/ice",
		GetIceAuth,
	},

	Route{
		"PostIceAuth",
		strings.ToUpper("Post"),
		"/ice",
		PostIceAuth,
	},

	Route{
		"GetTurnAuth",
		strings.ToUpper("Get"),
		"/",
		GetTurnAuth,
	},

	Route{
		"PostTurnAuth",
		strings.ToUpper("Post"),
		"/",
		PostTurnAuth,
	},
}
