name: Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Download modules
        run: go mod download
      - name: Go install
        run: go install
      - name: Test
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: github.repository == 'l7mp/stunner-auth-service'
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.out
          format: golang
